### ISSUE TITLE
Tiles are not available - map is empty

### ISSUE THREAD

**Issue by cgiovando** [hotosm/osm-analytics#72]
I believe this a cruncher issue, but reporting here since it's visible to the users on the frontend.

![screen shot 2017-08-22 at 23 12 18](https://user-images.githubusercontent.com/10201533/29587987-1a05fd0a-8790-11e7-9f04-4ce139337438.jpg)

OSMA is not usable at this point. @tiagojsag would be good if we can switch to the new cruncher as soon as possible. Please coordinate with @david-hotosm and @tyrasd

**Comment by tiagojsag** [comment]
@cgiovando on our side, we fixed the last remaining issues we had pending, and are just pending access to the historical tiles

thanks

**Comment by cgiovando** [comment]
That's good - then let's deploy and switch over to the new cruncher. We can put a note in the before/after tool saying that it will be restored next week, but for now let's go ahead with everything else.

Do you have a preview webapp that shows data from the new cruncher? Or otherwise please just send a PR to the [gh-pages branch](https://github.com/hotosm/osm-analytics/tree/gh-pages) which is the source of OSMA frontend.

**Comment by cgiovando** [comment]
Actually @tiagojsag I believe you just need to update line 2 of this file `https://github.com/hotosm/osm-analytics/blob/master/app/settings/settings.js` with the new source.

**Comment by tiagojsag** [comment]
@cgiovando as mentioned during our call, there are more changes needed than that, due to different tile availability on the new tile server/cruncher.

**Comment by cgiovando** [comment]
@tiagojsag - just to give you an update here - also in [gitter](https://gitter.im/hotosm/osm-analytics/archives/2017/08/24) - last night we updated `settings.js` to source tiles from `osm-analytics.vizzuality.com` 

Can you please send a PR for the frontend features that you guys improved/fixed? That should also fix km stats for roads still not working

@david-hotosm will also need to coordinate with you to change the tile source DNS to go back to its original URL `da-tiles.osm-analytics.org`

Thanks!

**Comment by tyrasd** [comment]
I believe this ticket can be closed by now?
